# Generated by Django 4.1 on 2022-09-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canarystr',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Notification E-Mail'),
        ),
        migrations.AlterField(
            model_name='canarystr',
            name='urldesc',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='canarystr',
            name='urlstr',
            field=models.CharField(max_length=60, verbose_name='URL String'),
        ),
    ]
