# Generated by Django 4.1 on 2022-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0002_alter_canarystr_email_alter_canarystr_urldesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlstr', models.CharField(max_length=60, verbose_name='URL String')),
                ('urldesc', models.CharField(max_length=250, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Notification E-Mail')),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Canarystr',
        ),
    ]
