# Generated by Django 4.1 on 2022-09-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0003_canarystring_delete_canarystr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canarystring',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
