# Generated by Django 4.1 on 2022-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0004_alter_canarystring_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server', models.CharField(max_length=100)),
                ('mail_user', models.CharField(max_length=100)),
                ('mail_passwd', models.CharField(max_length=150)),
            ],
        ),
    ]
