# Generated by Django 4.1 on 2022-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0005_canaryfile_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server', models.CharField(max_length=100, verbose_name='SMTP Server')),
                ('mail_user', models.CharField(max_length=100, verbose_name='SMTP Username')),
                ('mail_passwd', models.CharField(max_length=150, verbose_name='SMTP Password')),
                ('mail_port', models.CharField(max_length=3, verbose_name='SMTP Port')),
                ('mail_notification_address', models.EmailField(max_length=254, verbose_name='Notification E-Mail')),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AlterField(
            model_name='canaryfile',
            name='content',
            field=models.TextField(verbose_name='File Content'),
        ),
        migrations.AlterField(
            model_name='canaryfile',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='Filename'),
        ),
    ]
