# Generated by Django 4.1 on 2022-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0006_canarysetting_delete_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canarysetting',
            name='mail_sender_addr',
            field=models.EmailField(default='root@localhost', max_length=254, verbose_name='SMTP Sender Address'),
        ),
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_notification_address',
            field=models.EmailField(default='bob@server.example', max_length=254, verbose_name='Notification E-Mail'),
        ),
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_passwd',
            field=models.CharField(default='supersecurepassword', max_length=150, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_port',
            field=models.CharField(default='587', max_length=3, verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_server',
            field=models.CharField(default='localhost', max_length=100, verbose_name='SMTP Server'),
        ),
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_user',
            field=models.CharField(default='user@server.exmaple', max_length=100, verbose_name='SMTP Username'),
        ),
    ]
