# Generated by Django 4.1 on 2022-09-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0007_canarysetting_mail_sender_addr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canarysetting',
            name='mail_notification_address',
        ),
    ]
