# Generated by Django 4.1 on 2022-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0008_remove_canarysetting_mail_notification_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canarysetting',
            name='mail_sender_addr',
            field=models.EmailField(default='percula@localhost', max_length=254, verbose_name='SMTP Sender Address'),
        ),
    ]
